# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Climate Claims
tagline:          'Climate Claims'
description:      'In a world controlled by social media, determining the truth is as impartive as ever.'
url:              https://madiemckellar.github.io/hyde/
baseurl:          https://madiemckellar.github.io/hyde/

author:
  name:           'Madie McKellar'
  url:            https://www.linkedin.com/in/madie-mckellar-9708541b2/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/madiemckellar/hyde
