# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://madiemckellar.github.io/hyde/
baseurl:          https://madiemckellar.github.io/hyde/

author:
  name:           'Madie McKellar'
  url:            https://www.linkedin.com/in/madie-mckellar-9708541b2/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/madiemckellar/hyde
